### ISSUE TITLE
Support running gokart task.

### ISSUE THREAD

**Issue by Ryusuketa** [m3dev/thunderbolt#27]
To make data analysis easy, it would be great if running gokart task is supported in modules of thuderbolt like that 
```
def gokart_run(self, task_name, options: List[str]):
    gokart.run([task_name, *options])
    return self.get_data(task_name)
```

**Comment by vaaaaanquish** [comment]
@Ryusuketa This is a feature that should be included in gokart. Can I close?

**Comment by Ryusuketa** [comment]
@vaaaaanquish I agreed you. This issue is closed.
