### ISSUE TITLE
[Bug] get_task_df issues if workspace empty

### ISSUE THREAD

**Issue by TaylerUva** [m3dev/thunderbolt#45]
If all data is set to false then a KeyError exception will be raised if the workspace is empty.

Additionally, when workspace is empty the empty dataframe should contain the correct columns even if there are no rows. Right now the dataframe contains no columns when workspace is empty and all_data is set to true.

**Comment by hirosassa** [comment]
@TaylerUva Thanks for your report! This looks bug, will fix soon.

Anyway, where did you find a family of `gokart` OSSs? That's will be useful information for us and our OSSs.

**Comment by hirosassa** [comment]
@TaylerUva Hi! This issue is fix by #46 👍 
Thanks @yuta100101
