### ISSUE TITLE
[bug] Wrong input of local_cache.get in S3Client.get_tasks

### ISSUE THREAD

**Issue by kohei-shinden** [m3dev/thunderbolt#47]
### バグ

S3 からタスク一覧を取得しようとしており、以下のコードを実装しました。
以下のコードを実行した際に、`AttributeError: 'dict' object has no attribute 'split'` が発生します。

```.py
from thunderbolt.client.s3_client import S3Client
workspace_directory = 's3://bucket_name/prefix'
client = S3Client(workspace_directory=workspace_directory)
tasks_list = client.get_tasks()
```

`client.get_tasks()` においてエラーが発生します。

### 問題箇所

以下のコードが `client.get_tasks()` の問題箇所です。

https://github.com/m3dev/thunderbolt/blob/322af390805df368232e0b3d657c95a7472f8f30/thunderbolt/client/s3_client.py#L36

ここで、 `local_cache.get()` への入力 `x` は str 型でファイル名を渡す必要があることがわかります。

https://github.com/m3dev/thunderbolt/blob/322af390805df368232e0b3d657c95a7472f8f30/thunderbolt/client/local_cache.py#L18

しかし、`s3_client.get_tasks()` で実際に `local_cache.get()` へ渡されている `x` は以下のような dict 型になっています。
```
{'Key': '/resources/log/task_log/${task_name}.pkl', 'LastModified': datetime.datetime()}
```

### 解決方法

[問題箇所](https://github.com/m3dev/thunderbolt/blob/322af390805df368232e0b3d657c95a7472f8f30/thunderbolt/client/s3_client.py#L36
) を以下のように修正することで任意の動作を確認できました。

```.py
cache = self.local_cache.get(x['Key'])
```

前述の通り、`x` は dict であり、`x['Key']` がファイル名です。
そこで `local_cache.get()` に対して `x['Key']` を渡すように修正することで以下の形式の出力を得ました。

```
[{'task_name': '',
  'task_params': {},
  'task_log': {'file_path': ['s3://***.pkl']},
  'last_modified': datetime.datetime(),
  'task_hash': ''},
  ...
]
```

### 確認

もし、そもそもの用途が間違っていたらすみません。

**Comment by hirosassa** [comment]
@kohei-shinden 詳細な報告ありがとうございます！こちら確認してみますので少しお待ち下さい。

**Comment by Hi-king** [comment]
@kohei-shinden ありがとうございます。

現状の問題について調べてみました。結論から言うとおっしゃるとおりs3 + use_cacheでの動作に問題があり、修正が必要そうです。また、修正方法もxをcacheのkeyにしている部分をx['Key']にするという動作で良さそうです。

cache機能 https://github.com/m3dev/thunderbolt/pull/41 の実装時にgcsでしか動作確認がされておらず、レビューが漏れてしまっていました。

もしよろしければ修正PRをいただけると大変歓迎いたします。

急ぎのwork aroundとしては、S3Client(workspace_directory=workspace_directory, use_cache=False) として利用していただけると幸いです。

## クラウドサービス間での一貫性

### GCS

https://github.com/m3dev/thunderbolt/blob/322af390805df368232e0b3d657c95a7472f8f30/thunderbolt/client/gcs_client.py#L59

List[str]についてループをして、
metaは_get_gcs_object_info(x)で別途取得する
https://github.com/m3dev/thunderbolt/blob/322af390805df368232e0b3d657c95a7472f8f30/thunderbolt/client/gcs_client.py#L40


### S3

https://github.com/m3dev/thunderbolt/blob/322af390805df368232e0b3d657c95a7472f8f30/thunderbolt/client/s3_client.py#L60

List[Dict[str, Any]] (gcsで言うところのmeta)についてのループをしており、Dict[str, Any]をCacheのキーとしてしまっている

という設計のずれに問題がありそうです

## get -> setでのkeyの一貫性

https://github.com/m3dev/thunderbolt/blob/322af390805df368232e0b3d657c95a7472f8f30/thunderbolt/client/s3_client.py#L36
https://github.com/m3dev/thunderbolt/blob/322af390805df368232e0b3d657c95a7472f8f30/thunderbolt/client/s3_client.py#L51

こちらは現状両方xをkeyとしてdump, getをしているので一貫はしていそうです。両方をx[Key]に置き換えることで一貫した動作を得られそうです。
